language: rust

matrix:
  include:
    - rust: 1.32.0
      script: cargo test --verbose
    - rust: stable
      script: cargo test --verbose
    - rust: nightly
      script: cargo test --verbose

cache: cargo
